annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 28.4.3
description: ibm-pg-operator manages Postgres Clusters embedded in IBM Products -
  Cluster-scoped resources
home: https://www.ibm.com
keywords:
- postgresql
- postgres
- database
- sql
- ibm-pg-operator
maintainers:
- email: support@ibm.com
  name: IBM Support
name: ibm-pg-operator-cluster-scoped
sources:
- https://www.ibm.com
type: application
version: 28.4.3+20260820.165004.553
