---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.operatorNamespace }}
  labels:
    app.kubernetes.io/name: ibm-bob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
