{{- range (include "rhbkOperator.serviceAccounts" . | fromYamlArray) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "rhbkOperator.labels" $ | indent 4 }}
  name: {{ . }}
  namespace: {{ $.Values.global.operatorNamespace }}
{{- end -}}
