name: Issue for BOB
description: Report issues during your use of BOB.
title: "[BOB-Issue]: "
labels: ["needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for participating in the Bob evaluation! Your feedback helps us improve.
        
        **Note:** Labels will be automatically applied based on your selections below
  

  - type: dropdown
    id: issue-type
    attributes:
      label: Feedback Type
      description: "🏷️ Auto-labels: bug, performance, feature-request, usability, documentation, setup, mcp, security, feedback"
      options:
        - Bug / Error
        - Performance Issue
        - Feature Request
        - Usability Issue
        - Documentation Gap
        - Installation / Setup Problem
        - MCP Server Issue
        - Security Concern
        - General Feedback
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Impact
      description: "🏷️ Auto-labels: priority: blocker, critical, priority: high, priority: medium, priority: low, enhancement"
      options:
        - Blocker - Prevents BOB usage
        - Critical - Major impact on BOB usage
        - High - Affects key use cases
        - Medium - Affects secondary use cases
        - Low - Minor inconvenience
        - Enhancement - Nice to have
    validations:
      required: true

  - type: dropdown
    id: bob-product
    attributes:
      label: Bob Product
      description: "🏷️ Auto-labels: bob-ide, bobshell, multi-product"
      options:
        - Bob IDE (VS Code Extension)
        - Bob Shell 
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Bob Version
      description: Check Help > About in VS Code or run 'bob --version'
      placeholder: "e.g., 0.0.11"
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode (if applicable)
      description: "🏷️ Auto-labels: mode-ask, mode-code, mode-plan, mode-advanced, mode-custom"
      options:
        - "❓ Ask"
        - "💻 Code"
        - "📝 Plan"
        - "🛠️ Advanced"
        - Custom Mode
        - Not applicable
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 📋 Issue Details

  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: Brief, clear summary (1-2 sentences, minimum 30 characters)
      placeholder: "Example: Bob reports task completion but doesn't perform the requested action. The file remains unchanged despite Bob claiming success."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide detailed information about what happened (Minimum 50 characters)
      placeholder: |
        Describe the issue in detail:
        - What exactly happened?
        - What was the context?
        - What did Bob do or not do?
        - Any error messages or unexpected behavior?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🖥️ Environment & Configuration

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please fill in at least OS and Primary Language
      value: |
        **System:**
        - OS: [e.g., macOS 14.1, Windows 11, Ubuntu 22.04]
        - RAM: [e.g., 16GB]
        - CPU: [e.g., M1, Intel i7]
        
        **Project:**
        - Project Type: [e.g., Web app, CLI tool, Library]
        - Project Size: [e.g., Small (<100 files), Medium (100-1000), Large (>1000)]
        - Primary Language: [e.g., Python, JavaScript, Java]
    validations:
      required: true

  - type: textarea
    id: mcp-config
    attributes:
      label: MCP Configuration (if applicable)
      description: List configured MCP servers and their status
      placeholder: |
        - Server Name: [status: connected/disconnected]
        - Server Name: [status: connected/disconnected]
        
        Are you using MCP servers? If yes, which ones?
    validations:
      required: false