{{- if eq (lower (.Values.ibmUsageMetering.createRBAC | toString)) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ibm-usage-metering-operator
    component-id: {{ .Chart.Name }}
  name: ibm-usage-metering-operator
  namespace: {{ .Values.global.operatorNamespace | default .Release.Namespace  }}
{{- end }}
