apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component-id: '{{ .Chart.Name }}'
    icpdsupport/addOnId: ibm-pg-operator
    icpdsupport/app: database
    icpdsupport/module: ibm-pg-operator
  name: ibm-pg-operator
  namespace: '{{ .Values.global.operatorNamespace }}'
