{{- $watchNamespaces := $.Values.global.tetheredNamespaces | default list -}}
{{- if $.Values.global.instanceNamespace -}}
  {{- $watchNamespaces = append $watchNamespaces $.Values.global.instanceNamespace -}}
{{- end -}}
{{- $watchNamespaces = prepend $watchNamespaces $.Values.global.operatorNamespace }}
{{- range $namespace := uniq $watchNamespaces }}
---
apiVersion: pg.ibm.com/v1
kind: ImageCatalog
metadata:
  labels:
    component-id: '{{ $.Chart.Name }}'
    icpdsupport/addOnId: ibm-pg-operator
    icpdsupport/app: database
    icpdsupport/module: ibm-pg-operator
  name: ibm-pg-operator-operand-image-catalog
  namespace: {{ $namespace }}
spec:
  images:

  - image: {{ printf "%s/%s/%s:%s@%s" (default $.Values.global.imagePullPrefix $.Values.ibmPgOperator.devImagePullPrefix) $.Values.ibmPgOperator.operandImageRepository "ibm-pg-18" "18.6-v28.4.3" "sha256:8908bedd175d8e04878f505e986eb8240a9c1ef06f8f969803974151e5ea04d1" | quote }}
    major: 18

  - image: {{ printf "%s/%s/%s:%s@%s" (default $.Values.global.imagePullPrefix $.Values.ibmPgOperator.devImagePullPrefix) $.Values.ibmPgOperator.operandImageRepository "ibm-pg-17" "17.11-v28.4.3" "sha256:0f153e9d5900ba0864eb8d5b6924edfa01bf36f1a47defe3814e8e9514023074" | quote }}
    major: 17

  - image: {{ printf "%s/%s/%s:%s@%s" (default $.Values.global.imagePullPrefix $.Values.ibmPgOperator.devImagePullPrefix) $.Values.ibmPgOperator.operandImageRepository "ibm-pg-16" "16.15-v28.4.3" "sha256:5d120929b627afddc30ea67ee8fa7312217bd2a372ec2c0131eca68b82689fec" | quote }}
    major: 16

{{- end }}