apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component-id: '{{ .Chart.Name }}'
    icpdsupport/addOnId: ibm-pg-operator
    icpdsupport/app: database
    icpdsupport/module: ibm-pg-operator
  name: ibm-pg-operator-{{ .Values.global.operatorNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - patch
- apiGroups:
  - pg.ibm.com
  resources:
  - clusterimagecatalogs
  verbs:
  - get
  - list
  - watch
