{{- if and .Values.global.registryUsername .Values.global.registryPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret }}
  namespace: {{ .Values.global.instanceNamespace }}
  labels:
    app.kubernetes.io/name: ibm-bob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{- if eq .Values.global.imagePullPrefix "icr.io" -}}cp.{{- end -}}{{ .Values.global.imagePullPrefix }}": {
          "username": "{{ .Values.global.registryUsername }}",
          "auth": "{{ printf "%s:%s" .Values.global.registryUsername .Values.global.registryPassword | b64enc }}"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret }}
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    app.kubernetes.io/name: ibm-bob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{- if eq .Values.global.imagePullPrefix "icr.io" -}}cp.{{- end -}}{{ .Values.global.imagePullPrefix }}": {
          "username": "{{ .Values.global.registryUsername }}",
          "auth": "{{ printf "%s:%s" .Values.global.registryUsername .Values.global.registryPassword | b64enc }}"
        }
      }
    }
{{- end }}
