---
apiVersion: v1
kind: Secret
metadata:
  name: bob-inference-model-secrets
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    app.kubernetes.io/name: ibm-bob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.bob.modelGateway.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
