annotations:
  artifacthub.io/readme: |
    file://README.md
  charts.openshift.io/name: ibm-usage-metering
  charts.openshift.io/provider: IBM
  charts.openshift.io/source-url: https://github.ibm.com/cloud-license-reporter/ibm-usage-metering-operator
  charts.openshift.io/sources: https://github.ibm.com/cloud-license-reporter/ibm-usage-metering-operator
apiVersion: v2
appVersion: 1.0.6
description: 'A Helm chart for IBM Usage Metering installation. IBM products can integrate
  with Usage Metering Service (UMS) that is used to capture two types of product usage
  metrics: contractual metrics for compliance purposes, and adoption metrics for various
  scenarios related to usage analysis. UMS is intended to allow products capture business
  value metrics for the purpose of creating compliance evidence for the auditing purposes
  and visualizing metric usage in reporting tools.'
home: https://ibm.biz/usage_metering_service
icon: data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxu
  cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NzYiIGhlaWdodD0iNTc2IiB2aWV3Qm94
  PSIwIDAgNTc2IDU3NiI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgZmls
  bDogI2ZmZjsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2RlZnM+CiAgPHJlY3QgY2xhc3M9ImNscy0xIiB3
  aWR0aD0iNTc2IiBoZWlnaHQ9IjU3NiIvPgogIDxnPgogICAgPHJlY3QgeD0iMTI4IiB5PSIzNDIuOTQ5NSIg
  d2lkdGg9IjYyLjIyMjIiIGhlaWdodD0iOC44ODg5Ii8+CiAgICA8cmVjdCB4PSIxMjgiIHk9IjMyNS45Nzk3
  IiB3aWR0aD0iNjIuMjIyMiIgaGVpZ2h0PSI4Ljg4ODkiLz4KICAgIDxyZWN0IHg9IjE0NS43Nzc3IiB5PSIz
  MDkuMDEiIHdpZHRoPSIyNi42NjY3IiBoZWlnaHQ9IjguODg5Ii8+CiAgICA8cmVjdCB4PSIxNDUuNzc3NyIg
  eT0iMjkyLjA0MDQiIHdpZHRoPSIyNi42NjY3IiBoZWlnaHQ9IjguODg4OSIvPgogICAgPHJlY3QgeD0iMTQ1
  Ljc3NzciIHk9IjI3NS4wNzA2IiB3aWR0aD0iMjYuNjY2NyIgaGVpZ2h0PSI4Ljg4ODkiLz4KICAgIDxyZWN0
  IHg9IjE0NS43Nzc3IiB5PSIyNTguMTAxIiB3aWR0aD0iMjYuNjY2NyIgaGVpZ2h0PSI4Ljg4ODkiLz4KICAg
  IDxyZWN0IHg9IjEyOCIgeT0iMjQxLjEzMTMiIHdpZHRoPSI2Mi4yMjIyIiBoZWlnaHQ9IjguODg4OSIvPgog
  ICAgPHJlY3QgeD0iMTI4IiB5PSIyMjQuMTYxNyIgd2lkdGg9IjYyLjIyMjIiIGhlaWdodD0iOC44ODg5Ii8+
  CiAgICA8cGF0aCBkPSJNMTk5LjExMTIsMzM0Ljg2ODZoOTQuODQyYTMzLjcxMjEsMzMuNzEyMSwwLDAsMCwz
  LjU3Ni04Ljg4ODloLTk4LjQxOFoiLz4KICAgIDxwYXRoIGQ9Ik0yODYuNTI4NiwyOTIuMDRoLTY5LjY0djgu
  ODg4OGg3Ny4wNTQ3QTM0LjA3NTQsMzQuMDc1NCwwLDAsMCwyODYuNTI4NiwyOTIuMDRaIi8+CiAgICA8cGF0
  aCBkPSJNMjE2Ljg4ODksMjc1LjA3MDZWMjgzLjk2aDY5LjY0YTM0LjA3NzQsMzQuMDc3NCwwLDAsMCw3LjQx
  NS04Ljg4ODlaIi8+CiAgICA8cGF0aCBkPSJNMjkzLjk1MzIsMjQxLjEzMTNoLTk0Ljg0MlYyNTAuMDJoOTgu
  NDE4QTMzLjcxNDgsMzMuNzE0OCwwLDAsMCwyOTMuOTUzMiwyNDEuMTMxM1oiLz4KICAgIDxwYXRoIGQ9Ik0y
  NjQuNTY1NiwyMjQuMTYxN0gxOTkuMTExMnY4Ljg4ODhoODguMzVBMzMuODEzOCwzMy44MTM4LDAsMCwwLDI2
  NC41NjU2LDIyNC4xNjE3WiIvPgogICAgPHJlY3QgeD0iMjE2Ljg4ODkiIHk9IjI1OC4xMDEiIHdpZHRoPSIy
  Ni42NjY3IiBoZWlnaHQ9IjguODg4OSIvPgogICAgPHBhdGggZD0iTTI2OC42MDYxLDI2Ni45OWgyOC43MWEz
  My45NDkyLDMzLjk0OTIsMCwwLDAsMS4xODktOC44ODg5aC0yOS44OTlaIi8+CiAgICA8cmVjdCB4PSIyMTYu
  ODg4OSIgeT0iMzA5LjAxIiB3aWR0aD0iMjYuNjY2NyIgaGVpZ2h0PSI4Ljg4OSIvPgogICAgPHBhdGggZD0i
  TTI2OC42MDYxLDMwOS4wMXY4Ljg4OWgyOS44OTlhMzMuOTQ4OCwzMy45NDg4LDAsMCwwLTEuMTg5LTguODg5
  WiIvPgogICAgPHBhdGggZD0iTTE5OS4xMTEyLDM1MS43NWw2NS40NTQ0LjA4NzlhMzMuNjkyNiwzMy42OTI2
  LDAsMCwwLDIyLjg5NTktOC44ODg4aC04OC4zNVoiLz4KICAgIDxwb2x5Z29uIHBvaW50cz0iMzc2Ljg3NSAz
  NTEuODM4IDM3OS45NzkgMzQyLjk0OSAzNzMuNzk5IDM0Mi45NDkgMzc2Ljg3NSAzNTEuODM4Ii8+CiAgICA8
  cG9seWdvbiBwb2ludHM9IjM3MC45NjIgMzM0Ljg2OSAzODIuODE2IDMzNC44NjkgMzg1LjkzNiAzMjUuOTgg
  MzY3Ljg0MiAzMjUuOTggMzcwLjk2MiAzMzQuODY5Ii8+CiAgICA8cG9seWdvbiBwb2ludHM9IjM2NS4wMDUg
  MzE3Ljg5OSAzODguNzczIDMxNy44OTkgMzkxLjg5NCAzMDkuMDEgMzYxLjg4NCAzMDkuMDEgMzY1LjAwNSAz
  MTcuODk5Ii8+CiAgICA8cG9seWdvbiBwb2ludHM9IjM1OS4wNDcgMzAwLjkyOSAzOTQuNzMxIDMwMC45Mjkg
  Mzk3Ljg1MSAyOTIuMDQgMzU1LjkyNyAyOTIuMDQgMzU5LjA0NyAzMDAuOTI5Ii8+CiAgICA8cG9seWdvbiBw
  b2ludHM9IjMyMy41NTYgMjY2Ljk5IDM3MS41OCAyNjYuOTkgMzY4LjQ4OSAyNTguMTAxIDMyMy41NTYgMjU4
  LjEwMSAzMjMuNTU2IDI2Ni45OSIvPgogICAgPHBvbHlnb24gcG9pbnRzPSIzODguMDk5IDI1MC4wMiA0NDgg
  MjUwLjAyIDQ0OCAyNDEuMTMxIDM5MS4xOSAyNDEuMTMxIDM4OC4wOTkgMjUwLjAyIi8+CiAgICA8cG9seWdv
  biBwb2ludHM9IjM5Ny4wOTEgMjI0LjE2MiAzOTQgMjMzLjA1MSA0NDggMjMzLjA1MSA0NDggMjI0LjE2MiAz
  OTcuMDkxIDIyNC4xNjIiLz4KICAgIDxyZWN0IHg9IjMwNS43Nzc5IiB5PSIzNDIuOTQ5NSIgd2lkdGg9IjQ0
  LjQ0NDUiIGhlaWdodD0iOC44ODg5Ii8+CiAgICA8cmVjdCB4PSIzMDUuNzc3OSIgeT0iMzI1Ljk3OTciIHdp
  ZHRoPSI0NC40NDQ1IiBoZWlnaHQ9IjguODg4OSIvPgogICAgPHJlY3QgeD0iMzIzLjU1NTYiIHk9IjMwOS4w
  MSIgd2lkdGg9IjI2LjY2NjciIGhlaWdodD0iOC44ODkiLz4KICAgIDxyZWN0IHg9IjMyMy41NTU2IiB5PSIy
  OTIuMDQwNCIgd2lkdGg9IjI2LjY2NjciIGhlaWdodD0iOC44ODg5Ii8+CiAgICA8cG9seWdvbiBwb2ludHM9
  IjQzMC4yMjIgMjU4LjEwMSAzODUuMjg5IDI1OC4xMDEgMzgyLjE5OCAyNjYuOTkgNDMwLjIyMiAyNjYuOTkg
  NDMwLjIyMiAyNTguMTAxIi8+CiAgICA8cG9seWdvbiBwb2ludHM9IjQwMy41NTYgMjgzLjk2IDQzMC4yMjIg
  MjgzLjk2IDQzMC4yMjIgMjc1LjA3MSA0MDMuNTU2IDI3NS4wNzEgNDAzLjU1NiAyNzUuMDcxIDM3OS4zODcg
  Mjc1LjA3MSAzNzYuODg5IDI4Mi4yNTYgMzc0LjM5IDI3NS4wNzEgMzUwLjIyMiAyNzUuMDcxIDMyMy41NTYg
  Mjc1LjA3MSAzMjMuNTU2IDI4My45NiAzNTAuMjIyIDI4My45NiAzNTAuMjIyIDI3NS43OTEgMzUzLjA5IDI4
  My45NiA0MDAuNjg4IDI4My45NiA0MDMuNTU2IDI3NS43OTIgNDAzLjU1NiAyODMuOTYiLz4KICAgIDxyZWN0
  IHg9IjQwMy41NTU1IiB5PSIyOTIuMDQwNCIgd2lkdGg9IjI2LjY2NjciIGhlaWdodD0iOC44ODg5Ii8+CiAg
  ICA8cmVjdCB4PSI0MDMuNTU1NSIgeT0iMzA5LjAxIiB3aWR0aD0iMjYuNjY2NyIgaGVpZ2h0PSI4Ljg4OSIv
  PgogICAgPHJlY3QgeD0iNDAzLjU1NTUiIHk9IjMyNS45Nzk3IiB3aWR0aD0iNDQuNDQ0NSIgaGVpZ2h0PSI4
  Ljg4ODkiLz4KICAgIDxyZWN0IHg9IjQwMy41NTU1IiB5PSIzNDIuOTQ5NSIgd2lkdGg9IjQ0LjQ0NDUiIGhl
  aWdodD0iOC44ODg5Ii8+CiAgICA8cG9seWdvbiBwb2ludHM9IjM2NS42NzkgMjUwLjAyIDM2Mi41ODggMjQx
  LjEzMSAzMDUuNzc4IDI0MS4xMzEgMzA1Ljc3OCAyNTAuMDIgMzY1LjY3OSAyNTAuMDIiLz4KICAgIDxwb2x5
  Z29uIHBvaW50cz0iMzU5Ljc3OCAyMzMuMDUxIDM1Ni42ODcgMjI0LjE2MiAzMDUuNzc4IDIyNC4xNjIgMzA1
  Ljc3OCAyMzMuMDUxIDM1OS43NzggMjMzLjA1MSIvPgogIDwvZz4KPC9zdmc+Cg==
keywords:
- ibm
- metering
- usage
- monitoring
- chargeback
- showback
- cloudpak
maintainers:
- name: IBM
name: ibm-usage-metering
sources:
- https://github.ibm.com/cloud-license-reporter/ibm-usage-metering-operator
type: application
version: 1.0.6+20260525.133324.0
